import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faChevronDown } from '@fortawesome/free-solid-svg-icons'
import UiHeaderSection from '../resource/ui/UiHeaderSection'
import UiFooterSection from '../resource/ui/UiFooterSection'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>MORE Family Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='header-wrapper'>
        <UiHeaderSection />
      </header>

      <main className="section-wrapper">
        <div className="hero-section">
          <div className="hero-links">
            <p className="heading-caps">View Video</p>
            <p className="heading-caps">360° tour</p>
          </div>

          <div className="hero-main">
            <div className="hero-overlay">
              <div className="hero-desktop">
                <video src="/video/Treehouse_Sunset_1.mp4" autoPlay muted className='video-background'></video>
                <div className="text">
                  <h1 className='heading'>We Enrich Lives</h1>
                  <p className="body-text">Reconnect with life & one another</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className="footer-wrapper">
        <UiFooterSection />
      </footer>
    </div>
  )
}
